spring:
  data:

    elasticsearch:
      repositories:
        enabled: true

    redis:
      host: 133.186.241.167
      port: 6379
      database: 11
      password: "*N2vya7H@muDTwdNMR!"

  jpa:
    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!

  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-bookstore

  elasticsearch:
    uris: 115.94.72.198:9200
    username: elastic
    password: nhnacademy123!


server:
  shutdown: graceful

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
cloud:
  aws:
    credentials:
      access-key: f0a3fad864f3468293faa98da2807b67
      secret-key: 4f48b4901ffe47b0b64cb9d909e87364
    region:
      static: KR1
    s3:
      endpoint: https://kr1-api-object-storage.nhncloudservice.com
      bucket: nhnacademy-be6-3runner


springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /bookstore/docs/swagger


elasticsearch:
  key: b0FEM241QUJ6WmRyRUdYWG9LbUs6RVZ4WkNYM09TNTZvUU9qb0xxM09JZw==



db:
  driver: com.mysql.cj.jdbc.Driver
  url: 731e048dd73f4b429f4ef4f5ba6a6dbe
  # url: b6b9d1cb45ab4fb1b46637352b6a053c
  username: 83f7720a5c66449bae3b4948e07b111f
  password: 410f279ee5a54791b7dc0a1e87f94672
  initial-size: 5
  max-total: 20
  max-idle: 20
  min-idle: 5
