spring:
  config:
    activate:
      on-profile: dev

server:
  shutdown: graceful
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true

feign:
  coupon:
    url: localhost:8083
